name: CPP/CI

on:
  push:
    branches:
      - 'test'
  pull_request:
    branches:
      - 'test'
jobs:
  nest-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm i
      - run: npm run lint
  nest-test:
    needs: nest-linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm i
      - run: npm run test
